services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    env_file:
      - vars.env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pgnetwork
      - api_network

  api_server:
    container_name: rest_server
    build: ./src
    restart: always
    image: rest_server
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - api_network
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file:
      - vars.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - pgnetwork


networks:
  pgnetwork:
    driver: bridge
  api_network:
    driver: bridge

volumes:
  pg_data: