
CREATE TABLE IF NOT EXISTS TARI
(
    ID_TARA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NUME_TARA VARCHAR(50) NOT NULL,
    LATITUDINE DOUBLE PRECISION NOT NULL,
    LONGITUDINE DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS ORASE
(
    ID_ORAS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_TARA INT NOT NULL,
    NUME_ORAS VARCHAR(50) NOT NULL,
    LATITUDINE DOUBLE PRECISION NOT NULL,
    LONGITUDINE DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (ID_TARA) REFERENCES TARI(ID_TARA)
    UNIQUE (ID_TARA, NUME_ORAS)
);

CREATE TABLE IF NOT EXISTS TEMPERATURI
(
    ID_TEMPERATURA INT PRIMARY KEY AUTO_INCREMENT,
    ID_ORAS INT NOT NULL,
    `TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALOARE FLOAT NOT NULL,
    FOREIGN KEY (ID_ORAS) REFERENCES ORASE(ID_ORAS)
    UNIQUE (ID_ORAS, `TIMESTAMP`)
);