
CREATE TABLE IF NOT EXISTS TARI
(
    ID_TARA SERIAL,
    NUME_TARA VARCHAR(50) NOT NULL,
    LATITUDINE DOUBLE PRECISION NOT NULL,
    LONGITUDINE DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (ID_TARA)
);

CREATE TABLE IF NOT EXISTS ORASE
(
    ID_ORAS SERIAL PRIMARY KEY,
    ID_TARA INT NOT NULL,
    NUME_ORAS VARCHAR(50) NOT NULL,
    LATITUDINE DOUBLE PRECISION NOT NULL,
    LONGITUDINE DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (ID_TARA) REFERENCES TARI(ID_TARA),
    UNIQUE (ID_TARA, NUME_ORAS)
);

CREATE TABLE IF NOT EXISTS TEMPERATURI
(
    ID_TEMPERATURA SERIAL PRIMARY KEY,
    ID_ORAS INT NOT NULL,
    TIMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VALOARE FLOAT NOT NULL,
    FOREIGN KEY (ID_ORAS) REFERENCES ORASE(ID_ORAS),
    UNIQUE (ID_ORAS, TIMP)
);